EnvironmentalResources/config/routes.rb
Rails.application.routes.draw do
  get 'calendar/show'
  resources :resources, :events
  root :to => redirect('/resources')
end

CalendarExample::Application.routes.draw do
  resource :calendar, only: [:show], controller: :calendar
  root to: "calendar#show"
end

Rails.application.routes.draw do
    get "about", to: "about#index"
end

EnvironmentalResources/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

EnvironmentalResources/app/models/calendar.rb
class Calendar < Struct.new(:view, :date, :callback)
    HEADER = %w[Sunday Monday Tuesday Wednesday Thursday Friday Saturday]
    START_DAY = :sunday

    delegate :content_tag, to: :view

    def table
      content_tag :table, class: "calendar table table-bordered table-striped" do
        header + week_rows
      end
    end

    def header
      content_tag :tr do
        HEADER.map { |day| content_tag :th, day }.join.html_safe
      end
    end

    def week_rows
      weeks.map do |week|
        content_tag :tr do
          week.map { |day| day_cell(day) }.join.html_safe
        end
      end.join.html_safe
    end

    def day_cell(day)
        content_tag :td, view.capture(day, &callback), class: day_classes(day)
    end

    def day_classes(day)
      classes = []
      classes << "today" if day == Date.today
      classes << "not-month" if day.month != date.month
      classes.empty? ? nil : classes.join(" ")
    end

    def weeks
      first = date.beginning_of_month.beginning_of_week(START_DAY)
      last = date.end_of_month.end_of_week(START_DAY)
      (first..last).to_a.in_groups_of(7)
    end
end

EnvironmentalResources/app/models/event.rb
class Event < ActiveRecord::Base
    belongs_to :resource
end

EnvironmentalResources/app/models/resource.rb
class Resource < ActiveRecord::Base
    has_many :events
    accepts_nested_attributes_for :events
end

EnvironmentalResources/app/controllers/about_controller.rb
class AboutController < ApplicationController
    def index
    end
end

EnvironmentalResources/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

 def current_controller?(names)
    names.include?(current_controller)
  end

EnvironmentalResources/app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
  def show
  end
end

class CalendarController < ApplicationController
  def show
      @date = params[:date] ? Date.parse(params[:date]) : Date.today
  end
end

EnvironmentalResources/app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]

  # GET /events or /events.json
  def index
    @events = Event.all
  end

  # GET /events/1 or /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to resources_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:name, :description, :date, :resource)
    end
end

EnvironmentalResources/app/controllers/resources_controller.rb
class ResourcesController < ApplicationController
  before_action :set_resource, only: %i[ show edit update destroy ]

  # GET /resources or /resources.json
  def index
    @resources = Resource.all
  end

  # GET /resources/1 or /resources/1.json
  def show
  end

  # GET /resources/new
  def new
    @resource = Resource.new
  end

  # GET /resources/1/edit
  def edit
  end

  # POST /resources or /resources.json
  def create
    @resource = Resource.new(resource_params)

    respond_to do |format|
      if @resource.save
        format.html { redirect_to @resource, notice: "Resource was successfully created." }
        format.json { render :show, status: :created, location: @resource }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resources/1 or /resources/1.json
  def update
    respond_to do |format|
      if @resource.update(resource_params)
        format.html { redirect_to @resource, notice: "Resource was successfully updated." }
        format.json { render :show, status: :ok, location: @resource }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resources/1 or /resources/1.json
  def destroy
    @resource.destroy
    respond_to do |format|
      format.html { redirect_to resources_url, notice: "Resource was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resource
      @resource = Resource.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def resource_params
      params.require(:resource).permit(:title, :location, :description)
    end
end

EnvironmentalResources/app/helpers/application_helper.rb
module ApplicationHelper
end

EnvironmentalResources/app/helpers/calendar_helper.rb
module CalendarHelper
 def calendar(date = Date.today, &block)
    Calendar.new(self, date, block).table
  end

end

EnvironmentalResources/app/helpers/resources_helper.rb
module ResourcesHelper
end

EnvironmentalResources/app/views/calendar/show.html.erb
<h1>Calendar#show</h1>
<p>Find me in app/views/calendar/show.html.erb</p>

EnvironmentalResources/app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.text_field :date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

EnvironmentalResources/app/views/events/edit.html.erb
<h1>Editing Resource</h1>

<%= render 'form', resource: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', resources_path %>

EnvironmentalResources/app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="table-wrapper">
    <div class="table-title">
      <div class="row">
        <div class="col-sm-8"><h2>Resources</h2></div>
        <div class="col-sm-4">
          <%= link_to 'New Resource', new_resource_path, class: "btn btn-primary" %>
        </div>
      </div>
    </div>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Title</th>
          <th>Location</th>
          <th>Description</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @resources.each do |resource| %>
          <tr>
            <td><%= resource.title %></td>
            <td><%= resource.location %></td>
            <td><%= resource.description %></td>
            <td>
              <%= link_to 'Edit', edit_resource_path(resource), class: "btn btn-warning" %>
              <%= button_to 'Destroy', resource, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

EnvironmentalResources/app/views/events/new.html.erb
<h1>New Resource</h1>

<%= render 'form', resource: @resource %>

<%= link_to 'Back', resources_path %>

EnvironmentalResources/app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @resource.title %>
</p>

<p>
  <strong>Location:</strong>
  <%= @resource.location %>
</p>

<p>
  <strong>Description:</strong>
  <%= @resource.description %>
</p>


<%= link_to 'Edit', edit_resource_path(@resource) %> |
<%= link_to 'Back', resources_path %>

EnvironmentalResources/app/views/layouts/about/action.html.erb
<h1>About!</h1>

EnvironmentalResources/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EnvironmentalResources</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag "application.css" %>
    <%= stylesheet_link_tag "http://yandex.st/bootstrap/3.0.2/css/bootstrap.min.css", media: "all" %>
    <%= javascript_include_tag "http://yandex.st/bootstrap/3.0.2/js/bootstrap.min.js" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="#">Environmental Resources</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
    
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/resources">Resources</a>
          </li>
        </ul>
      </div>
    </nav>
    <%= yield %>
   <div class="card-deck">
      <div class="card">
        <img class="card-img-top" src="..." alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title">Volunteers</h5>
          <p class="card-text">If you're looking to volunteer, sign up for our email list below for updates on causes!</p>
          <a href="#" class="btn btn-primary">Sign up for our email list</a>
        </div>
      </div>
      <div class="card">
        <img class="card-img-top" src="..." alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title">Organizations</h5>
          <p class="card-text">If you have an organization that needs help, sign up and register your events!</p>
          <a href="#" class="btn btn-primary">Post events</a>
        </div>
      </div>
      <div class="card">
        <img class="card-img-top" src="..." alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title">Resources</h5>
          <p class="card-text">Keep track of various resources available to those in need below</p>
          <a href="#" class="btn btn-primary">Calendar</a>
        </div>
      </div>
    </div>
  </body>
</html>

EnvironmentalResources/app/views/resources/_form.html.erb
<%= form_with(model: resource, local: true) do |form| %>
  <% if resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
        <% resource.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

EnvironmentalResources/app/views/resources/edit.html.erb
<h1>Editing Resource</h1>

<%= render 'form', resource: @resource %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>

EnvironmentalResources/app/views/resources/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Resources</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Location</th>
      <th>Description</th>
      <th>Event date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @resources.each do |resource| %>
      <tr>
        <td><%= resource.title %></td>
        <td><%= resource.location %></td>
        <td><%= resource.description %></td>
        <td><%= resource.event_date %></td>
        <td><%= link_to 'Show', resource %></td>
        <td><%= link_to 'Edit', edit_resource_path(resource) %></td>
        <td><%= link_to 'Destroy', resource, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Resource', new_resource_path %>

EnvironmentalResources/app/views/resources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @resource.title %>
</p>

<p>
  <strong>Location:</strong>
  <%= @resource.location %>
</p>

<p>
  <strong>Description:</strong>
  <%= @resource.description %>
</p>

<p>
  <strong>Event date:</strong>
  <%= @resource.event_date %>
</p>

<%= link_to 'Edit', edit_resource_path(@resource) %> |
<%= link_to 'Back', resources_path %>